#require 'ruby-debug'; debugger
Buildr.settings.build['scala.version'] = '2.9.2'
Buildr.settings.build['scala.check.artifact'] = 'scalacheck_2.9.1'

require 'buildr/scala'


define 'prime_factors' do
  
end
